### ISSUE TITLE
BFArchive "extract" doesnt' work

### ISSUE THREAD

**Issue by catiamecc** [bigfix/bfarchive#7]
BFarchive version =9.3.1
BFArchive.exe -a C:\TEM\ExploreActions.pdf archive1
--> archive1 is fine created and the content displayed:

BFArchive.exe -l archive1
C:/TEM/ExploreActions.pdf

But the extract fails: 
BFArchive.exe -x archive1 decompress
Error: Failed to open or create file

-> decompress folder is being created but with nothing in it.

note: as per usage of the tool: 
BFArchive.exe
Usage:
  bfarchive -a <source file or directory> <name of archive>
  bfarchive -x <source archive> [target directory]
  bfarchive -l <source archive>

I can specify a source file or directory to compress but I discovered the extract issue is only when 
I compress a single file as in the above example. Compressing an entire directory compress/extract run fine.

**Comment by briangreenery** [comment]
I'm unable to reproduce this. Can you verify the version of BFArchive that you're using with `bfarchive --version`, and list the exact sequence of commands along with the complete directory contents before and after. Like, is it possible that 'decompress' is a file not a folder? Is it possible you're not using version `9.3.`?

**Comment by catiamecc** [comment]
Error Scenario :

C:\TEM\Tools\bfarchive-win-x64>BFArchive.exe -V
9.3.1

C:\TEM\Tools\bfarchive-win-x64>BFArchive.exe -a C:\TEM\ExploreActions.pdf archive1009

C:\TEM\Tools\bfarchive-win-x64>dir
 Volume in drive C has no label.
 Volume Serial Number is 9A19-F69B

 Directory of C:\TEM\Tools\bfarchive-win-x64

09/10/2015  11:53 AM    <DIR>          .
09/10/2015  11:53 AM    <DIR>          ..
09/10/2015  11:53 AM            11,666 archive1009
09/10/2015  11:52 AM           262,144 BFArchive.exe
               2 File(s)        273,810 bytes
               2 Dir(s)   2,559,021,056 bytes free

C:\TEM\Tools\bfarchive-win-x64>BFArchive.exe -l archive1009
C:/TEM/ExploreActions.pdf

C:\TEM\Tools\bfarchive-win-x64>BFArchive.exe -x archive1009 decompress
Error: Failed to open or create file

C:\TEM\Tools\bfarchive-win-x64>dir
 Volume in drive C has no label.
 Volume Serial Number is 9A19-F69B

 Directory of C:\TEM\Tools\bfarchive-win-x64

09/10/2015  11:54 AM    <DIR>          .
09/10/2015  11:54 AM    <DIR>          ..
09/10/2015  11:53 AM            11,666 archive1009
09/10/2015  11:52 AM           262,144 BFArchive.exe
09/10/2015  11:54 AM    <DIR>          decompress
               2 File(s)        273,810 bytes
               3 Dir(s)   2,558,951,424 bytes free

C:\TEM\Tools\bfarchive-win-x64>cd decompress

C:\TEM\Tools\bfarchive-win-x64\decompress>dir
 Volume in drive C has no label.
 Volume Serial Number is 9A19-F69B

 Directory of C:\TEM\Tools\bfarchive-win-x64\decompress

09/10/2015  11:54 AM    <DIR>          .
09/10/2015  11:54 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)   2,558,951,424 bytes free


************************************************************************
The problem occurs just in case you provide a full path in -a parameter. 
In case you provide only the file name to archive, tool works fine:

C:\TEM\Tools\bfarchive-win-x64\BFArchive.exe -a ExploreActions.pdf archive_new

C:\TEM>C:\TEM\Tools\bfarchive-win-x64\BFArchive.exe -a ExploreActions.pdf archive_new

C:\TEM>C:\TEM\Tools\bfarchive-win-x64\BFArchive.exe -l archive_new
ExploreActions.pdf

C:\TEM>C:\TEM\Tools\bfarchive-win-x64\BFArchive.exe -x archive_new decompress_new

C:\TEM>dir decompress_new
 Volume in drive C has no label.
 Volume Serial Number is 9A19-F69B

 Directory of C:\TEM\decompress_new

09/10/2015  11:59 AM    <DIR>          .
09/10/2015  11:59 AM    <DIR>          ..
07/14/2015  04:26 PM            14,325 ExploreActions.pdf
               1 File(s)         14,325 bytes
               2 Dir(s)   2,558,857,216 bytes free

**Comment by briangreenery** [comment]
Thanks! I understand.
